server:
  port: 2233
  recommend_key: 7mN[5LU@;WVA9H0YhKZw=8GO&hJgVmNS
  token_key: A9H0YhKZw=8GO&hJgVmNS
  token_expire_duration: 1
  cors:
    origins:
      - http://localhost:3000
    headers:
      - Content-Type
      - AccessToken
      - X-CSRF-Token
      - Authorization
      - Token
    methods:
      - POST
      - PUT
      - DELETE
      - GET
      - OPTIONS

mysql:
  user: root
  password: Chentyit123456
  host: 127.0.0.1
  port: 3306
  database: new_start_page_server_db
  max_open: 10
  max_idle: 5

redis:
  host: localhost
  port: 6379
  password: LsGJUYELrEnDuXSoFndX
  db_num: 5
  pool_size: 10
  key_prefix: start_page

logger:
  level: debug
  path: /Users/chentianyi/Program/Goland-workplace/new-start-page-sever/log/new-start-server-dev.log
  max_size: 100
  max_backups: 30
  max_age: 7
  compress: true